/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 143c4c7a259621942ac629790df202b5)
declare namespace Cloudflare {
	interface Env {
		DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").DurableObject>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
