/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4de5960053833661983fa8d58f757687)
declare namespace Cloudflare {
	interface Env {
		DURABLE_OBJECT: DurableObjectNamespace<import("./index").DurableObject>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
