/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./src/worker-configuration.d.ts --include-runtime=false` (hash: 83ea9e8a9065cd742696e754da0eab07)
declare namespace Cloudflare {
	interface Env {
		DURABLE_OBJECT: DurableObjectNamespace<import("./index").MyDurableObject>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
